apiVersion: v1
kind: Secret
metadata:
  name: cm-tap-gui-sa-overlay
  namespace: tap-install
stringData:
  cm-tap-gui-sa-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "cm-sa"}})
    ---
    #@overlay/match missing_ok=True
    imagePullSecrets:
    #@overlay/append
    - name: install-registry-dockerconfig
 