---
apiVersion: v1
kind: Secret
metadata:
  name: my-dockerhub-credentials-dummy
  annotations:
    secretgen.carvel.dev/image-pull-secret: "my-dockerhub-credentials"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K