---
apiVersion: v1
kind: Secret
metadata:
  name: user-registry-dockerconfig
  annotations:
    secretgen.carvel.dev/image-pull-secret: "user-registry-dockerconfig"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K