---
apiVersion: v1
kind: Secret
metadata:
  name: install-registry-dockerconfig
  namespace: tap-gui
  annotations:
    secretgen.carvel.dev/image-pull-secret: "install-registry-dockerconfig"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K