apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: my-registry-credentials
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install